### ISSUE TITLE
[ bug ] unauthorized has the wrong status code

### ISSUE THREAD

**Issue by Zeus3hd** [mhmdtshref/backend-starter#1]
`src/utils/response.utils.ts`

```
const unauthorized = (response: Response) => response.status(201).json({ error: 'Unauthorized' });
```

the returned status is 201 when it should be 401.

I recommend using constants for common statuses and instead of passing the hard coded code pass the constant.

**Comment by mhmdtshref** [comment]
Righty, thank you for correcting @Zeus3hd :D
