### ISSUE TITLE
[ suggestion ] use config library for env variables

### ISSUE THREAD

**Issue by Zeus3hd** [mhmdtshref/backend-starter#2]
in `src/environments.ts` there's a loop that checks for missing variables.
while it does the job and there's nothing wrong with it
```
const missedVariables = requiredVariables.filter((v) => !process.env[v]);
```

I suggest using this library which handles config:
https://www.npmjs.com/package/config

and getting a config constant would be as easy as:

`const port = config.get<number>('port')`

**Comment by mhmdtshref** [comment]
Thank you Ahd!
I think your code filter looks better than the for-loop. Will change it.

But I don't see think I need to use the [config](https://www.npmjs.com/package/config) package. I don't think it will add something different to the project.
